name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
            AWS_EC2_METADATA_DISABLED: "true"
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ec2-user/github/ &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin/main &&
              '
                                    
          #ssh -t -t -o ServerAliveInterval=300 -i private_key ${USER_NAME}@${HOSTNAME}
           #ssh -t -t -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 
           #echo ${USER_NAME} 
           #ssh -o ServerAliveInterval=300  ${USER_NAME}@{HOSTNAME}
           #echo $HOSTNAME
           #cd /home/ec2-user/github/ &&
           #git checkout main &&
           #git fetch --all &&
           #git reset --hard origin/main &&
           #git pull origin main && 
              # Now we have got the access of EC2 and we will start the deploy .
              #scp .github/workflows/scripts/startserver.sh ${USER_NAME}@${HOSTNAME}:/home/ec2-user/github/
              #cp .github/workflows/scripts/startserver.sh /home/ec2-user/github/ 
              #cd /home/ec2-user/github/startserver.sh
              
